docs: extend CONTRIBUTING guide
php-epm/epm pull request #2
Opened 2024-10-27 10:41 UTC by castarco

Although the project remains private for now, it's still relevant to improve this document.

## Changes
- Move `CONTRIBUTING.md` to `docs/`. We'll need this directory anyway, and it makes more sense to have it here than in `.github/` (Github also accepts it if it's in `docs/`)
- Introduce some guidelines.

2024-10-27 19:31 UTC, stratdes requested changes

2024-10-27 19:31 UTC, stratdes commented on docs/CONTRIBUTING.md
> +SPDX-FileCopyrightText: 2024 Alex Hernández <info@alexhernandez.info>, Andres Correa <andreu@kindspells.dev>
Tilde in Andrés

2024-10-27 19:31 UTC, stratdes commented on docs/CONTRIBUTING.md
> +  - Backwards compatibility is almost sacred, please try to preserve it.
Instead of “almost sacred” I would say “mandatory most of the times”

2024-10-27 19:31 UTC, stratdes commented on docs/CONTRIBUTING.md
> +  - Try to respect the current coding style, to avoid style inconsistencies.
Instead of “try to respect”, I would just say “respect”.

2024-10-27 20:51 UTC, castarco commented on docs/CONTRIBUTING.md
> +  - Try to respect the current coding style, to avoid style inconsistencies.
fixed

2024-10-27 20:51 UTC, castarco commented on docs/CONTRIBUTING.md
> +  - Backwards compatibility is almost sacred, please try to preserve it.
fixed

2024-10-27 20:51 UTC, castarco commented on docs/CONTRIBUTING.md
> +SPDX-FileCopyrightText: 2024 Alex Hernández <info@alexhernandez.info>, Andres Correa <andreu@kindspells.dev>
fixed

2024-10-28 07:04 UTC, stratdes approved these changes

2024-10-28 07:55 UTC, merged