docs: introduce EIPs process
php-epm/epm pull request #3
Opened 2024-10-27 17:50 UTC by castarco

This PR introduces a new documentation process: EIPs (EPM Improvement Proposals).

The idea behind EIPs is to ensure that all relevant technical decisions are properly discussed and documented. In turn, having everything properly documented is desirable because it will help us to avoid knowledge silos and relying too much on implicit knowledge.

2024-10-28 08:24 UTC, stratdes requested changes

2024-10-28 08:24 UTC, stratdes commented on docs/eips/development/dev-0000-eips.md
> +```
Tilde

2024-10-28 08:24 UTC, stratdes commented on docs/eips/development/dev-0000-eips.md
> +
Extra space

2024-10-28 08:24 UTC, stratdes commented on docs/eips/development/dev-0000-eips.md
> +
Extra space

2024-10-28 08:24 UTC, stratdes commented on docs/eips/development/dev-0000-eips.md
> +`[dev|feat|arch]-xxxx-short-title.md`, where `xxxx` is the number of the EIP
Wouldn't be better to have xxxx at the beginning to have ordering based on it?

2024-10-28 08:24 UTC, stratdes commented on docs/eips/development/dev-0000-eips.md
> +You can use the template [dev-0000-eips.md](dev-0000-eips.md) as a starting
Same, have xxxx at the beginning.

2024-10-28 08:24 UTC, stratdes commented on docs/eips/development/dev-0000-eips.md
> +Example: `# dev-0000: EPM Improvement Proposal (EIP) Process`.
Same

2024-10-28 08:24 UTC, stratdes commented on docs/eips/development/dev-0000-eips.md
> +* `Created:` Creation date in the format YYYY-mm-dd
I would add "at", so Created at:

2024-10-28 08:24 UTC, stratdes commented on docs/eips/development/dev-0000-eips.md
> +included in a subdirectory for that EIP which MUST be named `files/eip-XXXX`
Again, I would set XXXX at the beginning.

2024-10-28 08:24 UTC, stratdes commented on docs/eips/development/dev-0000-eips.md
> +A EIP may only change status from `Draft` to `Proposed`, when the author deems
As far as I understand, we are asking contributors to write actual code **_before_** we actually have decided to move on with this EIP. Is this necessary or even fair?

2024-10-28 08:24 UTC, stratdes commented on docs/eips/development/dev-0000-eips.md
> +
Extra space

2024-10-28 08:24 UTC, stratdes commented on docs/eips/development/dev-0000-eips.md
> +understand and follow the process. It also builds on the insight others have
Instead of "and follow the process", where "process" is redundant, I would say "and follow them."

2024-10-28 08:24 UTC, stratdes commented on docs/eips/development/dev-0000-eips.md
> +
Extra space.

2024-10-28 08:24 UTC, stratdes commented on docs/eips/development/dev-0000-eips.md
> +
Extra space.

2024-10-28 08:24 UTC, stratdes commented on docs/eips/development/dev-0000-eips.md
> +
Extra space.

2024-10-28 08:24 UTC, stratdes commented on docs/eips/development/files/eip-0000/process.png
Do we need to have both png and svg files?

2024-10-28 08:24 UTC, stratdes commented on docs/eips/index.md
> +  - `eips/development`: `dev-0000-short-title.md`
xxxx at the beginning, you know.

2024-11-01 11:19 UTC, castarco commented on docs/eips/development/files/eip-0000/process.png
svg: the "source code" of the image.
png: "compiled" version.

At the time of creating them (some years ago) some browsers trugglrd to show svg images properly in some contexts (Gitlab rendered markdown)

2024-11-01 11:20 UTC, castarco commented on docs/eips/development/dev-0000-eips.md
> +`[dev|feat|arch]-xxxx-short-title.md`, where `xxxx` is the number of the EIP
These are namespaces, each one has its own sequence.

We could have a unique sequence, but then it's not just a matter of reordering these two bits of info in the filenames.

2024-11-02 09:55 UTC, castarco commented on docs/eips/development/dev-0000-eips.md
> +A EIP may only change status from `Draft` to `Proposed`, when the author deems
No.

- `Draft` is an acceptable status and does not require anyone to write any code, that's the stage at which the community is discussing whether to proceed with it or not.
- `Proposed` comes after that, it serves to indicate that the EIP is already in a state where we have a reference implementation and the proposal is ready (or almost ready) to be in a working state.

2024-11-02 09:57 UTC, castarco commented on docs/eips/development/dev-0000-eips.md
> +
This is on purpose.

2024-11-02 10:02 UTC, castarco commented on docs/eips/development/dev-0000-eips.md
> +understand and follow the process. It also builds on the insight others have
There is a mismatch between singular and plural in your replacement proposal 🧐

2024-11-02 10:11 UTC, castarco commented on docs/eips/development/dev-0000-eips.md
> +```
It's customary to write these change requests below the problematic line, not above.

When I'm in the "Files Changed" section I can easily see the relation between your comment and the code, but that's not the same in the Conversations section, where I only see the line
```
''' // imagine 3 backticks here instead of single quotes
```

2024-11-02 10:18 UTC, castarco commented on docs/eips/development/dev-0000-eips.md
> +```
Fixed

2024-11-23 10:08 UTC, castarco commented
I recuse myself from participating in this project any further. I might fork it, but not work in this repository under the current terms.

2024-11-23 10:08 UTC, closed without merging